module.exports = {
    AUTO_VIEW_STATUS: 'true',
    AUTO_LIKE_STATUS: 'true',
    AUTO_RECORDING: 'true',
    AUTO_LIKE_EMOJI: ['🌸', '🪴', '💫', '🍂', '🌟','🫀', '👀', '🤖', '🚩', '🥰', '🗿', '💜', '💙', '🌝', '🖤', '💚'],
    PREFIX: '.',
    MAX_RETRIES: 3,
    GROUP_INVITE_LINK: 'https://chat.whatsapp.com/mAZGH6fgSR3s',
    ADMIN_LIST_PATH: './admin.json',
    IMAGE_PATH: 'https://files.catbox.moe/3e7u52.jpg',
    NEWSLETTER_JID: '1203637750390@newsletter',
    NEWSLETTER_MESSAGE_ID: '428',
    OTP_EXPIRY: 300000,
    NEWS_JSON_URL: '',
    BOT_NAME: 'laki md',
    OWNER_NAME: 'lakshan',
    OWNER_NUMBER: '94789227570',
    BOT_VERSION: '1.0.2',
    BOT_FOOTER: '> ᴘᴏᴡᴇʀᴇᴅ ʙʏ lakshan',
    CHANNEL_LINK: 'https://whatsapp.com/channel/0029VbCDScJ7IUYSRgvRzj2W',
};
